INSERT INTO gustos (gustos_name)
VALUES ("Vainilla"),
("Chocolate"),
("Frutilla"),
("Crema del cielo"),
("Dulce de leche"),
("Frambuesa"),
("Limón"),
("Naranja"),
("Crema americana"),
("Banana"),
("Menta granizada"),
("Granizado"),
("Cereza"),
("Coco"),
("Mousse de chocolate"),
("Tiramisú"),
("Café"),
("Avellana"),
("Arándano"),
("Mousse de limón"),
("Zanahoria y naranja"),
("Durazno"),
("Manzana verde"),
("Leche merengada"),
("Mantecol"),
("Chantilly"),
("Yogur con frutas"),
("Maracuyá"),
("Uva"),
("Mora");

INSERT INTO gustos_especiales (gustos_esp_name)
VALUES ("Wasabi"),
("Queso azul"),
("Aceite de oliva"),
("Té verde matcha"),
("Cactus"),
("Pimienta rosa"),
("Albahaca"),
("Tomate cherry"),
("Curry"),
("Jengibre con miel"),
("Lavanda"),
("Rosa"),
("Sésamo negro"),
("Charcoal (carbón activado)"),
("Calabaza especiada"),
("Humo"),
("Cerveza artesanal"),
("Champán con frutilla"),
("Vino Malbec"),
("Ajo caramelizado"),
("Palta (aguacate)"),
("Anís estrellado"),
("Pepino con menta"),
("Pan de jengibre"),
("Tocino con maple"),
("Miso dulce"),
("Chili picante"),
("Café turco"),
("Blue cheese con peras"),
("Wasabi con chocolate blanco");

INSERT INTO salsas (salsa_name)
VALUES ("Salsa de frutilla"),
("Salsa de chocolate"),
("Salsa de dulce de leche"),
("Salsa de caramelo"),
("Salsa de frutos rojos"),
("Salsa de maracuyá"),
("Salsa de mango"),
("Salsa de kiwi"),
("Salsa de arándanos"),
("Salsa de limón"),
("Salsa de naranja"),
("Salsa de frambuesa"),
("Salsa de durazno"),
("Salsa de manzana verde"),
("Salsa de cereza"),
("Salsa de coco"),
("Salsa de frutos tropicales"),
("Salsa de lavanda"),
("Salsa de menta"),
("Salsa de café"),
("Salsa de vino tinto"),
("Salsa de ron con pasas"),
("Salsa de jengibre y miel"),
("Salsa de té verde"),
("Salsa de avellanas"),
("Salsa de pistacho"),
("Salsa de almendras"),
("Salsa de rosas"),
("Salsa de violetas"),
("Salsa de especias chai");

INSERT INTO bocadillos (bocadillos_name)
VALUES ("Obleas"),
("Chocolate KitKat"),
("Rocklets"),
("Chispas de chocolate"),
("Frutos secos"),
("Galletitas Oreo"),
("Brownie"),
("Galletitas de vainilla"),
("Cubitos de chocolate blanco"),
("Gomitas"),
("Nueces caramelizadas"),
("Crocante de maní"),
("Granas de colores"),
("Cereales"),
("Pedacitos de alfajor"),
("Cookies trozadas"),
("Marshmallows"),
("Trozos de banana"),
("Trozos de frutilla"),
("Coco rallado"),
("Caramelo duro"),
("Barra de cereal"),
("Churros en miniatura"),
("Turrón picado"),
("Bombones"),
("Confites de chocolate"),
("Mermelada espesa"),
("Bizcochuelo de chocolate"),
("Pedacitos de waffle"),
("Trozos de tarta de limón");




-- Insertar dos tiendas (store)
INSERT INTO store (address_id) VALUES (101), (102);

-- Insertar dos empleados (staff), cada uno asignado a una tienda distinta
INSERT INTO staff (first_name, last_name, store_id)
VALUES 
  ('Diego', 'Ajata Ledezma', 1),
  ('Juanma', 'Parrado', 2);

-- Insertar un inventario para cada tienda
INSERT INTO payment (pago, store_id, staff_id)
VALUES
  (3300, 1, 1),
  (6500, 2, 2),
  (3900, 1, 2),
  (7800, 2, 1),
  (2500, 1, 1),
  (3300, 2, 2),
  (4500, 1, 2),
  (1200, 2, 1);